apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: he60xvvpw-python 
  janus-idp.io/tekton: he60xvvpw-python
  backstage.io/kubernetes-id: he60xvvpw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: he60xvvpw-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  