apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: he60xvvpw-python
  janus-idp.io/tekton: he60xvvpw-python
  backstage.io/kubernetes-id: he60xvvpw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: he60xvvpw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
